export const HOTEL_INFO = {
  name: "Kalika Hotel & Lodge",
  subtitle: "Guest House & Boutique Lodge",
  address: "Itahari-9, Buspark, Sunsari, Koshi Province, Nepal",
  phone: "9842042150",
  altPhone: "+977 25 580123",
  email: "kalikahotel.itahari@gmail.com",
  panNumber: "602394812",
  vatRate: 13,
  tagline: "Authentic Hospitality & Tranquil Comfort in the Heart of Itahari",
  checkInTime: "12:00 PM",
  checkOutTime: "11:00 AM",
};

export const INITIAL_CATEGORIES = [
  {
    id: "cat-1",
    name: "Standard Room",
    code: "STD",
    basePrice: 1800,
    maxOccupancy: { adults: 2, children: 1 },
    bedType: "Queen Bed",
    description: "Cozy, quiet and comfortable room equipped with all basic essentials for travelers and short stays.",
    defaultAmenities: ["High-speed Wi-Fi", "Attached Bathroom", "24/7 Hot Water", "Ceiling Fan", "Work Desk"],
    image: "/images/room1.jpeg",
  },
  {
    id: "cat-2",
    name: "Deluxe Room",
    code: "DLX",
    basePrice: 2800,
    maxOccupancy: { adults: 2, children: 1 },
    bedType: "King Bed",
    description: "Spacious air-conditioned room with modern wooden furnishings, LED TV, and peaceful garden or city views.",
    defaultAmenities: ["Air Conditioning", "High-speed Wi-Fi", "Smart LED TV", "Attached Modern Bathroom", "24/7 Hot Shower", "Tea/Coffee Maker", "Room Service"],
    image: "/images/room2.jpeg",
  },
  {
    id: "cat-3",
    name: "Super Deluxe",
    code: "SDLX",
    basePrice: 3800,
    maxOccupancy: { adults: 3, children: 1 },
    bedType: "King Bed + Single Bed",
    description: "Premium room featuring a private scenic balcony, sound-insulated glazing, luxury bedding, and mini-fridge.",
    defaultAmenities: ["Private Balcony", "Split Air Conditioner", "High-speed Wi-Fi", "43\" Smart TV", "Mini Refrigerator", "Luxury Toiletries", "24/7 Room Service"],
    image: "/images/room3.jpeg",
  },
  {
    id: "cat-4",
    name: "Executive Suite",
    code: "EXEC",
    basePrice: 5500,
    maxOccupancy: { adults: 3, children: 2 },
    bedType: "Super King Bed",
    description: "The pinnacle of comfort at Kalika Hotel. Separate living lounge area, executive work desk, bathtub, and panoramic views.",
    defaultAmenities: ["Living Room Lounge", "Bathtub & Rain Shower", "Split AC", "55\" 4K TV", "Mini Bar", "Welcome Drink", "Express Laundry", "Priority Room Service"],
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
  },
];

export const INITIAL_ROOMS = [
  {
    id: "room-101",
    roomNumber: "101",
    category: "Standard Room",
    floor: 1,
    pricePerNight: 1800,
    bedType: "1 Queen Bed",
    maxGuests: 2,
    roomSize: "260 sq.ft",
    view: "Courtyard View",
    amenities: ["High-speed Wi-Fi", "Attached Bathroom", "24/7 Hot Water", "Ceiling Fan", "Work Desk"],
    images: [
      "/images/room1.jpeg",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1000&q=80",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    description: "Nicely decorated ground floor standard room near reception. Perfect for short visits, business travelers, or transit guests at Itahari Buspark.",
    status: "available",
    rating: 4.6,
  },
  {
    id: "room-102",
    roomNumber: "102",
    category: "Deluxe Room",
    floor: 1,
    pricePerNight: 2800,
    bedType: "1 King Bed",
    maxGuests: 2,
    roomSize: "320 sq.ft",
    view: "Garden View",
    amenities: ["Air Conditioning", "High-speed Wi-Fi", "Smart LED TV", "Attached Modern Bathroom", "24/7 Hot Shower", "Tea/Coffee Maker", "Room Service"],
    images: [
      "/images/room2.jpeg",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80",
    ],
    videoUrl: "https://www.youtube.com/embed/7PIji8OubXU",
    description: "Serene Deluxe Room with warm ambient lighting, split air conditioning, fast optical Wi-Fi, and plush spring mattress.",
    status: "occupied", // Sample active stay for checkout & order demo
    currentBookingId: "KB-2026-101",
    rating: 4.8,
  },
  {
    id: "room-201",
    roomNumber: "201",
    category: "Super Deluxe",
    floor: 2,
    pricePerNight: 3800,
    bedType: "1 King Bed + 1 Single Bed",
    maxGuests: 3,
    roomSize: "380 sq.ft",
    view: "City & Buspark View with Balcony",
    amenities: ["Private Balcony", "Split Air Conditioner", "High-speed Wi-Fi", "43\" Smart TV", "Mini Refrigerator", "Luxury Toiletries", "24/7 Room Service"],
    images: [
      "/images/room3.jpeg",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1000&q=80",
    ],
    videoUrl: "https://www.youtube.com/embed/ScMzIvxBSi4",
    description: "Elevated second-floor Super Deluxe room boasting a private breezy balcony, tea station, mini-fridge, and blackout curtains.",
    status: "occupied", // Sample active stay for checkout & order demo
    currentBookingId: "KB-2026-102",
    rating: 4.9,
  },
  {
    id: "room-202",
    roomNumber: "202",
    category: "Standard Room",
    floor: 2,
    pricePerNight: 1800,
    bedType: "2 Twin Beds",
    maxGuests: 2,
    roomSize: "280 sq.ft",
    view: "Street View",
    amenities: ["High-speed Wi-Fi", "Attached Bathroom", "24/7 Hot Water", "Ceiling Fan", "Luggage Rack"],
    images: [
      "/images/room1.jpeg",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1000&q=80",
    ],
    videoUrl: "",
    description: "Twin-bedded standard room suitable for friends, colleagues, or backpackers stopping in Itahari.",
    status: "cleaning",
    rating: 4.5,
  },
  {
    id: "room-301",
    roomNumber: "301",
    category: "Executive Suite",
    floor: 3,
    pricePerNight: 5500,
    bedType: "Super King Bed",
    maxGuests: 4,
    roomSize: "550 sq.ft",
    view: "Panoramic Koshi Horizon View",
    amenities: ["Living Room Lounge", "Bathtub & Rain Shower", "Split AC", "55\" 4K TV", "Mini Bar", "Welcome Drink", "Express Laundry", "Priority Room Service"],
    images: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80",
    ],
    videoUrl: "https://www.youtube.com/embed/9No-FiEInLA",
    description: "Top floor luxury suite with dedicated living room, plush velvet sofa, bathtub with mountain view, and VIP room service.",
    status: "available",
    rating: 5.0,
  },
  {
    id: "room-302",
    roomNumber: "302",
    category: "Deluxe Room",
    floor: 3,
    pricePerNight: 2800,
    bedType: "1 King Bed",
    maxGuests: 2,
    roomSize: "320 sq.ft",
    view: "Garden View",
    amenities: ["Air Conditioning", "High-speed Wi-Fi", "Smart LED TV", "Attached Modern Bathroom", "24/7 Hot Shower", "Tea/Coffee Maker"],
    images: [
      "/images/room2.jpeg",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1000&q=80",
    ],
    videoUrl: "",
    description: "Bright third-floor deluxe room featuring large soundproof windows and morning sunlight.",
    status: "available",
    rating: 4.7,
  },
];

export const INITIAL_FOOD_ITEMS = [
  {
    id: "food-1",
    name: "Charcoal Jheer Sekuwa Set",
    category: "Snacks & Sekuwa",
    price: 450,
    description: "Authentic charcoal grilled marinated chicken & pork sekuwa served in a traditional wicker basket with fresh spicy green and sesame chutneys, pickles, and beaten rice.",
    image: "/images/sekuwa.jpeg",
    isVeg: false,
    isAvailable: true,
  },
  {
    id: "food-2",
    name: "Authentic Nepali Thakali Khana Set",
    category: "Mains & Thali",
    price: 550,
    description: "Traditional Thakali brass plate meal: steamed fragrant rice, local chicken curry, black lentils (Jimbu Daal), seasonal green saag, aloo bodi tama, crispy papad, gundruk achar, and fresh curd (dahi).",
    image: "/images/thakali.jpeg",
    isVeg: false,
    isAvailable: true,
  },
  {
    id: "food-3",
    name: "Steamed Chicken Momo (10 pcs)",
    category: "Snacks & Sekuwa",
    price: 240,
    description: "Handcrafted juicy dumplings filled with seasoned minced chicken, herbs, and onions, served piping hot with authentic spicy sesame-tomato dipping sauce.",
    image: "/images/Momo.jpeg",
    isVeg: false,
    isAvailable: true,
  },
  {
    id: "food-4",
    name: "Special Continental Breakfast",
    category: "Breakfast",
    price: 380,
    description: "Toasted bread with butter & fruit jam, two farm-fresh eggs (fried or scrambled), hash brown, and fresh fruit juice.",
    image: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    isAvailable: true,
  },
  {
    id: "food-5",
    name: "Paneer Butter Masala with 2 Naan",
    category: "Mains & Thali",
    price: 420,
    description: "Cottage cheese simmered in rich buttery makhani gravy, served with two fresh butter tandoori naans.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    isAvailable: true,
  },
  {
    id: "food-6",
    name: "Special Masala Milk Tea (Pot)",
    category: "Beverages",
    price: 150,
    description: "Fresh mountain CTC tea brewed with organic cow milk, green cardamom, cloves, and ginger.",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    isAvailable: true,
  },
  {
    id: "food-7",
    name: "Ilam Cold Coffee with Ice Cream",
    category: "Beverages",
    price: 220,
    description: "Chilled blended espresso coffee topped with rich vanilla ice cream and chocolate drizzle.",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80",
    isVeg: true,
    isAvailable: true,
  },
  {
    id: "food-8",
    name: "Sizzling Chocolate Brownie with Ice Cream",
    category: "Dessert",
    price: 280,
    description: "Warm fudgy chocolate brownie topped with a scoop of rich chocolate ice cream and drizzled with hot melted chocolate fudge.",
    image: "/images/dessert.jpeg",
    isVeg: true,
    isAvailable: true,
  },
];

export const INITIAL_BOOKINGS = [
  {
    id: "book-1",
    bookingId: "KB-2026-101",
    roomId: "room-102",
    roomNumber: "102",
    roomCategory: "Deluxe Room",
    guest: {
      fullName: "Ramesh Karki",
      phone: "9842109876",
      email: "ramesh.karki@gmail.com",
      idCardNumber: "12-01-76-00431",
      address: "Biratnagar, Morang",
    },
    bookingType: "online",
    checkInDate: "2026-10-04",
    checkOutDate: "2026-10-06",
    actualCheckIn: "2026-10-04T13:30:00.000Z",
    actualCheckOut: null,
    totalNights: 2,
    roomRatePerNight: 2800,
    totalRoomCharge: 5600,
    advancePaid: 2800,
    paymentMethod: "esewa",
    paymentStatus: "partially_paid",
    status: "checked_in",
    specialRequests: "Non-smoking room, extra pillow requested",
    createdAt: "2026-10-03T10:15:00.000Z",
  },
  {
    id: "book-2",
    bookingId: "KB-2026-102",
    roomId: "room-201",
    roomNumber: "201",
    roomCategory: "Super Deluxe",
    guest: {
      fullName: "Sita Sharma",
      phone: "9812345678",
      email: "sita.sharma@yahoo.com",
      idCardNumber: "06-03-74-12903",
      address: "Kathmandu",
    },
    bookingType: "offline_walkin",
    checkInDate: "2026-10-05",
    checkOutDate: "2026-10-07",
    actualCheckIn: "2026-10-05T14:00:00.000Z",
    actualCheckOut: null,
    totalNights: 2,
    roomRatePerNight: 3800,
    totalRoomCharge: 7600,
    advancePaid: 7600,
    paymentMethod: "cash",
    paymentStatus: "paid",
    status: "checked_in",
    specialRequests: "Early morning tea at 6:30 AM",
    createdAt: "2026-10-05T08:20:00.000Z",
  },
];

export const INITIAL_ORDERS = [
  {
    id: "ord-1",
    orderNumber: "ORD-9102",
    roomNumber: "102",
    bookingId: "KB-2026-101",
    guestName: "Ramesh Karki",
    items: [
      { name: "Nepali Khaja Set (Sekuwa & Chiura)", price: 450, quantity: 2, itemTotal: 900 },
      { name: "Special Masala Milk Tea (Pot)", price: 150, quantity: 1, itemTotal: 150 },
    ],
    totalAmount: 1050,
    specialInstructions: "Make tea extra strong, please deliver by 7:30 PM",
    status: "delivered", // pending | preparing | delivered | cancelled
    isBilledToRoom: true,
    createdAt: "2026-10-04T18:40:00.000Z",
  },
  {
    id: "ord-2",
    orderNumber: "ORD-9103",
    roomNumber: "102",
    bookingId: "KB-2026-101",
    guestName: "Ramesh Karki",
    items: [
      { name: "Steamed Chicken Momo (10 pcs)", price: 240, quantity: 2, itemTotal: 480 },
      { name: "Cold Soft Drink / Soda", price: 80, quantity: 2, itemTotal: 160 },
    ],
    totalAmount: 640,
    specialInstructions: "Extra spicy dipping sauce",
    status: "preparing",
    isBilledToRoom: true,
    createdAt: "2026-10-05T19:15:00.000Z",
  },
  {
    id: "ord-3",
    orderNumber: "ORD-9201",
    roomNumber: "201",
    bookingId: "KB-2026-102",
    guestName: "Sita Sharma",
    items: [
      { name: "Chicken Thakali Thali Set", price: 550, quantity: 1, itemTotal: 550 },
      { name: "Warm Gulab Jamun (2 pcs)", price: 140, quantity: 1, itemTotal: 140 },
    ],
    totalAmount: 690,
    specialInstructions: "Less chili in curry",
    status: "delivered",
    isBilledToRoom: true,
    createdAt: "2026-10-05T15:20:00.000Z",
  },
];

export const INITIAL_BILLS = [
  {
    id: "bill-100",
    billNumber: "INV-2026-0038",
    bookingId: "KB-2026-095",
    roomNumber: "302",
    roomCategory: "Deluxe Room",
    guest: {
      fullName: "Bikash Adhikari",
      phone: "9852011223",
      email: "bikash@example.com",
      idCardNumber: "01-05-72-88123",
      address: "Dharan-12",
    },
    checkInDate: "2026-10-02",
    checkOutDate: "2026-10-04",
    nights: 2,
    roomRate: 2800,
    roomCharges: 5600,
    orders: [
      { orderNumber: "ORD-8941", itemsSummary: "Chicken Momo (x2), Cold Drink (x2)", amount: 640 },
      { orderNumber: "ORD-8949", itemsSummary: "Continental Breakfast (x1)", amount: 380 },
    ],
    totalOrdersAmount: 1020,
    extraCharges: 200,
    extraChargesDescription: "Laundry service (2 shirts)",
    subtotal: 6820,
    discount: 200,
    taxRate: 13,
    taxAmount: 861,
    serviceChargeRate: 0,
    serviceChargeAmount: 0,
    grandTotal: 7481,
    advancePaid: 2800,
    balanceDue: 0,
    amountPaidAtCheckout: 4681,
    paymentMethod: "esewa",
    paymentStatus: "paid",
    createdAt: "2026-10-04T11:15:00.000Z",
  },
];
